version: '3.3'
services:
  db:
    image: mysql:latest
    command: [ "--max_connections=1000" ]
    restart: always
    environment:
      MYSQL_DATABASE: 'thaneea'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'thaneea'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'U8fqpaa5KH3CDFng'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'dV8Ew6sGwsXPCXGU'
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 20000
        hard: 40000