CREATE USER 'student_1'@'%';
ALTER USER 'student_1'@'%'
IDENTIFIED BY 'student_1' ;
GRANT Alter ON student_1.* TO 'student_1'@'%';
GRANT Create ON student_1.* TO 'student_1'@'%';
GRANT Create view ON student_1.* TO 'student_1'@'%';
GRANT Delete ON student_1.* TO 'student_1'@'%';
GRANT Drop ON student_1.* TO 'student_1'@'%';
GRANT Grant option ON student_1.* TO 'student_1'@'%';
GRANT Index ON student_1.* TO 'student_1'@'%';
GRANT Insert ON student_1.* TO 'student_1'@'%';
GRANT References ON student_1.* TO 'student_1'@'%';
GRANT Select ON student_1.* TO 'student_1'@'%';
GRANT Show view ON student_1.* TO 'student_1'@'%';
GRANT Trigger ON student_1.* TO 'student_1'@'%';
GRANT Update ON student_1.* TO 'student_1'@'%';
GRANT Alter routine ON student_1.* TO 'student_1'@'%';
GRANT Create routine ON student_1.* TO 'student_1'@'%';
GRANT Create temporary tables ON student_1.* TO 'student_1'@'%';
GRANT Execute ON student_1.* TO 'student_1'@'%';
GRANT Lock tables ON student_1.* TO 'student_1'@'%';

CREATE USER 'student_2'@'%';
ALTER USER 'student_2'@'%'
IDENTIFIED BY 'student_2' ;
GRANT Alter ON student_2.* TO 'student_2'@'%';
GRANT Create ON student_2.* TO 'student_2'@'%';
GRANT Create view ON student_2.* TO 'student_2'@'%';
GRANT Delete ON student_2.* TO 'student_2'@'%';
GRANT Drop ON student_2.* TO 'student_2'@'%';
GRANT Grant option ON student_2.* TO 'student_2'@'%';
GRANT Index ON student_2.* TO 'student_2'@'%';
GRANT Insert ON student_2.* TO 'student_2'@'%';
GRANT References ON student_2.* TO 'student_2'@'%';
GRANT Select ON student_2.* TO 'student_2'@'%';
GRANT Show view ON student_2.* TO 'student_2'@'%';
GRANT Trigger ON student_2.* TO 'student_2'@'%';
GRANT Update ON student_2.* TO 'student_2'@'%';
GRANT Alter routine ON student_2.* TO 'student_2'@'%';
GRANT Create routine ON student_2.* TO 'student_2'@'%';
GRANT Create temporary tables ON student_2.* TO 'student_2'@'%';
GRANT Execute ON student_2.* TO 'student_2'@'%';
GRANT Lock tables ON student_2.* TO 'student_2'@'%';

CREATE USER 'student_3'@'%';
ALTER USER 'student_3'@'%'
IDENTIFIED BY 'student_3' ;
GRANT Alter ON student_3.* TO 'student_3'@'%';
GRANT Create ON student_3.* TO 'student_3'@'%';
GRANT Create view ON student_3.* TO 'student_3'@'%';
GRANT Delete ON student_3.* TO 'student_3'@'%';
GRANT Drop ON student_3.* TO 'student_3'@'%';
GRANT Grant option ON student_3.* TO 'student_3'@'%';
GRANT Index ON student_3.* TO 'student_3'@'%';
GRANT Insert ON student_3.* TO 'student_3'@'%';
GRANT References ON student_3.* TO 'student_3'@'%';
GRANT Select ON student_3.* TO 'student_3'@'%';
GRANT Show view ON student_3.* TO 'student_3'@'%';
GRANT Trigger ON student_3.* TO 'student_3'@'%';
GRANT Update ON student_3.* TO 'student_3'@'%';
GRANT Alter routine ON student_3.* TO 'student_3'@'%';
GRANT Create routine ON student_3.* TO 'student_3'@'%';
GRANT Create temporary tables ON student_3.* TO 'student_3'@'%';
GRANT Execute ON student_3.* TO 'student_3'@'%';
GRANT Lock tables ON student_3.* TO 'student_3'@'%';

CREATE USER 'student_4'@'%';
ALTER USER 'student_4'@'%'
IDENTIFIED BY 'student_4' ;
GRANT Alter ON student_4.* TO 'student_4'@'%';
GRANT Create ON student_4.* TO 'student_4'@'%';
GRANT Create view ON student_4.* TO 'student_4'@'%';
GRANT Delete ON student_4.* TO 'student_4'@'%';
GRANT Drop ON student_4.* TO 'student_4'@'%';
GRANT Grant option ON student_4.* TO 'student_4'@'%';
GRANT Index ON student_4.* TO 'student_4'@'%';
GRANT Insert ON student_4.* TO 'student_4'@'%';
GRANT References ON student_4.* TO 'student_4'@'%';
GRANT Select ON student_4.* TO 'student_4'@'%';
GRANT Show view ON student_4.* TO 'student_4'@'%';
GRANT Trigger ON student_4.* TO 'student_4'@'%';
GRANT Update ON student_4.* TO 'student_4'@'%';
GRANT Alter routine ON student_4.* TO 'student_4'@'%';
GRANT Create routine ON student_4.* TO 'student_4'@'%';
GRANT Create temporary tables ON student_4.* TO 'student_4'@'%';
GRANT Execute ON student_4.* TO 'student_4'@'%';
GRANT Lock tables ON student_4.* TO 'student_4'@'%';

CREATE USER 'student_5'@'%';
ALTER USER 'student_5'@'%'
IDENTIFIED BY 'student_5' ;
GRANT Alter ON student_5.* TO 'student_5'@'%';
GRANT Create ON student_5.* TO 'student_5'@'%';
GRANT Create view ON student_5.* TO 'student_5'@'%';
GRANT Delete ON student_5.* TO 'student_5'@'%';
GRANT Drop ON student_5.* TO 'student_5'@'%';
GRANT Grant option ON student_5.* TO 'student_5'@'%';
GRANT Index ON student_5.* TO 'student_5'@'%';
GRANT Insert ON student_5.* TO 'student_5'@'%';
GRANT References ON student_5.* TO 'student_5'@'%';
GRANT Select ON student_5.* TO 'student_5'@'%';
GRANT Show view ON student_5.* TO 'student_5'@'%';
GRANT Trigger ON student_5.* TO 'student_5'@'%';
GRANT Update ON student_5.* TO 'student_5'@'%';
GRANT Alter routine ON student_5.* TO 'student_5'@'%';
GRANT Create routine ON student_5.* TO 'student_5'@'%';
GRANT Create temporary tables ON student_5.* TO 'student_5'@'%';
GRANT Execute ON student_5.* TO 'student_5'@'%';
GRANT Lock tables ON student_5.* TO 'student_5'@'%';

CREATE USER 'student_6'@'%';
ALTER USER 'student_6'@'%'
IDENTIFIED BY 'student_6' ;
GRANT Alter ON student_6.* TO 'student_6'@'%';
GRANT Create ON student_6.* TO 'student_6'@'%';
GRANT Create view ON student_6.* TO 'student_6'@'%';
GRANT Delete ON student_6.* TO 'student_6'@'%';
GRANT Drop ON student_6.* TO 'student_6'@'%';
GRANT Grant option ON student_6.* TO 'student_6'@'%';
GRANT Index ON student_6.* TO 'student_6'@'%';
GRANT Insert ON student_6.* TO 'student_6'@'%';
GRANT References ON student_6.* TO 'student_6'@'%';
GRANT Select ON student_6.* TO 'student_6'@'%';
GRANT Show view ON student_6.* TO 'student_6'@'%';
GRANT Trigger ON student_6.* TO 'student_6'@'%';
GRANT Update ON student_6.* TO 'student_6'@'%';
GRANT Alter routine ON student_6.* TO 'student_6'@'%';
GRANT Create routine ON student_6.* TO 'student_6'@'%';
GRANT Create temporary tables ON student_6.* TO 'student_6'@'%';
GRANT Execute ON student_6.* TO 'student_6'@'%';
GRANT Lock tables ON student_6.* TO 'student_6'@'%';

CREATE USER 'student_7'@'%';
ALTER USER 'student_7'@'%'
IDENTIFIED BY 'student_7' ;
GRANT Alter ON student_7.* TO 'student_7'@'%';
GRANT Create ON student_7.* TO 'student_7'@'%';
GRANT Create view ON student_7.* TO 'student_7'@'%';
GRANT Delete ON student_7.* TO 'student_7'@'%';
GRANT Drop ON student_7.* TO 'student_7'@'%';
GRANT Grant option ON student_7.* TO 'student_7'@'%';
GRANT Index ON student_7.* TO 'student_7'@'%';
GRANT Insert ON student_7.* TO 'student_7'@'%';
GRANT References ON student_7.* TO 'student_7'@'%';
GRANT Select ON student_7.* TO 'student_7'@'%';
GRANT Show view ON student_7.* TO 'student_7'@'%';
GRANT Trigger ON student_7.* TO 'student_7'@'%';
GRANT Update ON student_7.* TO 'student_7'@'%';
GRANT Alter routine ON student_7.* TO 'student_7'@'%';
GRANT Create routine ON student_7.* TO 'student_7'@'%';
GRANT Create temporary tables ON student_7.* TO 'student_7'@'%';
GRANT Execute ON student_7.* TO 'student_7'@'%';
GRANT Lock tables ON student_7.* TO 'student_7'@'%';

CREATE USER 'student_8'@'%';
ALTER USER 'student_8'@'%'
IDENTIFIED BY 'student_8' ;
GRANT Alter ON student_8.* TO 'student_8'@'%';
GRANT Create ON student_8.* TO 'student_8'@'%';
GRANT Create view ON student_8.* TO 'student_8'@'%';
GRANT Delete ON student_8.* TO 'student_8'@'%';
GRANT Drop ON student_8.* TO 'student_8'@'%';
GRANT Grant option ON student_8.* TO 'student_8'@'%';
GRANT Index ON student_8.* TO 'student_8'@'%';
GRANT Insert ON student_8.* TO 'student_8'@'%';
GRANT References ON student_8.* TO 'student_8'@'%';
GRANT Select ON student_8.* TO 'student_8'@'%';
GRANT Show view ON student_8.* TO 'student_8'@'%';
GRANT Trigger ON student_8.* TO 'student_8'@'%';
GRANT Update ON student_8.* TO 'student_8'@'%';
GRANT Alter routine ON student_8.* TO 'student_8'@'%';
GRANT Create routine ON student_8.* TO 'student_8'@'%';
GRANT Create temporary tables ON student_8.* TO 'student_8'@'%';
GRANT Execute ON student_8.* TO 'student_8'@'%';
GRANT Lock tables ON student_8.* TO 'student_8'@'%';

CREATE USER 'student_9'@'%';
ALTER USER 'student_9'@'%'
IDENTIFIED BY 'student_9' ;
GRANT Alter ON student_9.* TO 'student_9'@'%';
GRANT Create ON student_9.* TO 'student_9'@'%';
GRANT Create view ON student_9.* TO 'student_9'@'%';
GRANT Delete ON student_9.* TO 'student_9'@'%';
GRANT Drop ON student_9.* TO 'student_9'@'%';
GRANT Grant option ON student_9.* TO 'student_9'@'%';
GRANT Index ON student_9.* TO 'student_9'@'%';
GRANT Insert ON student_9.* TO 'student_9'@'%';
GRANT References ON student_9.* TO 'student_9'@'%';
GRANT Select ON student_9.* TO 'student_9'@'%';
GRANT Show view ON student_9.* TO 'student_9'@'%';
GRANT Trigger ON student_9.* TO 'student_9'@'%';
GRANT Update ON student_9.* TO 'student_9'@'%';
GRANT Alter routine ON student_9.* TO 'student_9'@'%';
GRANT Create routine ON student_9.* TO 'student_9'@'%';
GRANT Create temporary tables ON student_9.* TO 'student_9'@'%';
GRANT Execute ON student_9.* TO 'student_9'@'%';
GRANT Lock tables ON student_9.* TO 'student_9'@'%';

CREATE USER 'student_10'@'%';
ALTER USER 'student_10'@'%'
IDENTIFIED BY 'student_10' ;
GRANT Alter ON student_10.* TO 'student_10'@'%';
GRANT Create ON student_10.* TO 'student_10'@'%';
GRANT Create view ON student_10.* TO 'student_10'@'%';
GRANT Delete ON student_10.* TO 'student_10'@'%';
GRANT Drop ON student_10.* TO 'student_10'@'%';
GRANT Grant option ON student_10.* TO 'student_10'@'%';
GRANT Index ON student_10.* TO 'student_10'@'%';
GRANT Insert ON student_10.* TO 'student_10'@'%';
GRANT References ON student_10.* TO 'student_10'@'%';
GRANT Select ON student_10.* TO 'student_10'@'%';
GRANT Show view ON student_10.* TO 'student_10'@'%';
GRANT Trigger ON student_10.* TO 'student_10'@'%';
GRANT Update ON student_10.* TO 'student_10'@'%';
GRANT Alter routine ON student_10.* TO 'student_10'@'%';
GRANT Create routine ON student_10.* TO 'student_10'@'%';
GRANT Create temporary tables ON student_10.* TO 'student_10'@'%';
GRANT Execute ON student_10.* TO 'student_10'@'%';
GRANT Lock tables ON student_10.* TO 'student_10'@'%';

CREATE USER 'student_11'@'%';
ALTER USER 'student_11'@'%'
IDENTIFIED BY 'student_11' ;
GRANT Alter ON student_11.* TO 'student_11'@'%';
GRANT Create ON student_11.* TO 'student_11'@'%';
GRANT Create view ON student_11.* TO 'student_11'@'%';
GRANT Delete ON student_11.* TO 'student_11'@'%';
GRANT Drop ON student_11.* TO 'student_11'@'%';
GRANT Grant option ON student_11.* TO 'student_11'@'%';
GRANT Index ON student_11.* TO 'student_11'@'%';
GRANT Insert ON student_11.* TO 'student_11'@'%';
GRANT References ON student_11.* TO 'student_11'@'%';
GRANT Select ON student_11.* TO 'student_11'@'%';
GRANT Show view ON student_11.* TO 'student_11'@'%';
GRANT Trigger ON student_11.* TO 'student_11'@'%';
GRANT Update ON student_11.* TO 'student_11'@'%';
GRANT Alter routine ON student_11.* TO 'student_11'@'%';
GRANT Create routine ON student_11.* TO 'student_11'@'%';
GRANT Create temporary tables ON student_11.* TO 'student_11'@'%';
GRANT Execute ON student_11.* TO 'student_11'@'%';
GRANT Lock tables ON student_11.* TO 'student_11'@'%';

CREATE USER 'student_12'@'%';
ALTER USER 'student_12'@'%'
IDENTIFIED BY 'student_12' ;
GRANT Alter ON student_12.* TO 'student_12'@'%';
GRANT Create ON student_12.* TO 'student_12'@'%';
GRANT Create view ON student_12.* TO 'student_12'@'%';
GRANT Delete ON student_12.* TO 'student_12'@'%';
GRANT Drop ON student_12.* TO 'student_12'@'%';
GRANT Grant option ON student_12.* TO 'student_12'@'%';
GRANT Index ON student_12.* TO 'student_12'@'%';
GRANT Insert ON student_12.* TO 'student_12'@'%';
GRANT References ON student_12.* TO 'student_12'@'%';
GRANT Select ON student_12.* TO 'student_12'@'%';
GRANT Show view ON student_12.* TO 'student_12'@'%';
GRANT Trigger ON student_12.* TO 'student_12'@'%';
GRANT Update ON student_12.* TO 'student_12'@'%';
GRANT Alter routine ON student_12.* TO 'student_12'@'%';
GRANT Create routine ON student_12.* TO 'student_12'@'%';
GRANT Create temporary tables ON student_12.* TO 'student_12'@'%';
GRANT Execute ON student_12.* TO 'student_12'@'%';
GRANT Lock tables ON student_12.* TO 'student_12'@'%';

CREATE USER 'student_13'@'%';
ALTER USER 'student_13'@'%'
IDENTIFIED BY 'student_13' ;
GRANT Alter ON student_13.* TO 'student_13'@'%';
GRANT Create ON student_13.* TO 'student_13'@'%';
GRANT Create view ON student_13.* TO 'student_13'@'%';
GRANT Delete ON student_13.* TO 'student_13'@'%';
GRANT Drop ON student_13.* TO 'student_13'@'%';
GRANT Grant option ON student_13.* TO 'student_13'@'%';
GRANT Index ON student_13.* TO 'student_13'@'%';
GRANT Insert ON student_13.* TO 'student_13'@'%';
GRANT References ON student_13.* TO 'student_13'@'%';
GRANT Select ON student_13.* TO 'student_13'@'%';
GRANT Show view ON student_13.* TO 'student_13'@'%';
GRANT Trigger ON student_13.* TO 'student_13'@'%';
GRANT Update ON student_13.* TO 'student_13'@'%';
GRANT Alter routine ON student_13.* TO 'student_13'@'%';
GRANT Create routine ON student_13.* TO 'student_13'@'%';
GRANT Create temporary tables ON student_13.* TO 'student_13'@'%';
GRANT Execute ON student_13.* TO 'student_13'@'%';
GRANT Lock tables ON student_13.* TO 'student_13'@'%';

CREATE USER 'student_14'@'%';
ALTER USER 'student_14'@'%'
IDENTIFIED BY 'student_14' ;
GRANT Alter ON student_14.* TO 'student_14'@'%';
GRANT Create ON student_14.* TO 'student_14'@'%';
GRANT Create view ON student_14.* TO 'student_14'@'%';
GRANT Delete ON student_14.* TO 'student_14'@'%';
GRANT Drop ON student_14.* TO 'student_14'@'%';
GRANT Grant option ON student_14.* TO 'student_14'@'%';
GRANT Index ON student_14.* TO 'student_14'@'%';
GRANT Insert ON student_14.* TO 'student_14'@'%';
GRANT References ON student_14.* TO 'student_14'@'%';
GRANT Select ON student_14.* TO 'student_14'@'%';
GRANT Show view ON student_14.* TO 'student_14'@'%';
GRANT Trigger ON student_14.* TO 'student_14'@'%';
GRANT Update ON student_14.* TO 'student_14'@'%';
GRANT Alter routine ON student_14.* TO 'student_14'@'%';
GRANT Create routine ON student_14.* TO 'student_14'@'%';
GRANT Create temporary tables ON student_14.* TO 'student_14'@'%';
GRANT Execute ON student_14.* TO 'student_14'@'%';
GRANT Lock tables ON student_14.* TO 'student_14'@'%';

CREATE USER 'student_15'@'%';
ALTER USER 'student_15'@'%'
IDENTIFIED BY 'student_15' ;
GRANT Alter ON student_15.* TO 'student_15'@'%';
GRANT Create ON student_15.* TO 'student_15'@'%';
GRANT Create view ON student_15.* TO 'student_15'@'%';
GRANT Delete ON student_15.* TO 'student_15'@'%';
GRANT Drop ON student_15.* TO 'student_15'@'%';
GRANT Grant option ON student_15.* TO 'student_15'@'%';
GRANT Index ON student_15.* TO 'student_15'@'%';
GRANT Insert ON student_15.* TO 'student_15'@'%';
GRANT References ON student_15.* TO 'student_15'@'%';
GRANT Select ON student_15.* TO 'student_15'@'%';
GRANT Show view ON student_15.* TO 'student_15'@'%';
GRANT Trigger ON student_15.* TO 'student_15'@'%';
GRANT Update ON student_15.* TO 'student_15'@'%';
GRANT Alter routine ON student_15.* TO 'student_15'@'%';
GRANT Create routine ON student_15.* TO 'student_15'@'%';
GRANT Create temporary tables ON student_15.* TO 'student_15'@'%';
GRANT Execute ON student_15.* TO 'student_15'@'%';
GRANT Lock tables ON student_15.* TO 'student_15'@'%';

CREATE USER 'student_16'@'%';
ALTER USER 'student_16'@'%'
IDENTIFIED BY 'student_16' ;
GRANT Alter ON student_16.* TO 'student_16'@'%';
GRANT Create ON student_16.* TO 'student_16'@'%';
GRANT Create view ON student_16.* TO 'student_16'@'%';
GRANT Delete ON student_16.* TO 'student_16'@'%';
GRANT Drop ON student_16.* TO 'student_16'@'%';
GRANT Grant option ON student_16.* TO 'student_16'@'%';
GRANT Index ON student_16.* TO 'student_16'@'%';
GRANT Insert ON student_16.* TO 'student_16'@'%';
GRANT References ON student_16.* TO 'student_16'@'%';
GRANT Select ON student_16.* TO 'student_16'@'%';
GRANT Show view ON student_16.* TO 'student_16'@'%';
GRANT Trigger ON student_16.* TO 'student_16'@'%';
GRANT Update ON student_16.* TO 'student_16'@'%';
GRANT Alter routine ON student_16.* TO 'student_16'@'%';
GRANT Create routine ON student_16.* TO 'student_16'@'%';
GRANT Create temporary tables ON student_16.* TO 'student_16'@'%';
GRANT Execute ON student_16.* TO 'student_16'@'%';
GRANT Lock tables ON student_16.* TO 'student_16'@'%';

CREATE USER 'student_17'@'%';
ALTER USER 'student_17'@'%'
IDENTIFIED BY 'student_17' ;
GRANT Alter ON student_17.* TO 'student_17'@'%';
GRANT Create ON student_17.* TO 'student_17'@'%';
GRANT Create view ON student_17.* TO 'student_17'@'%';
GRANT Delete ON student_17.* TO 'student_17'@'%';
GRANT Drop ON student_17.* TO 'student_17'@'%';
GRANT Grant option ON student_17.* TO 'student_17'@'%';
GRANT Index ON student_17.* TO 'student_17'@'%';
GRANT Insert ON student_17.* TO 'student_17'@'%';
GRANT References ON student_17.* TO 'student_17'@'%';
GRANT Select ON student_17.* TO 'student_17'@'%';
GRANT Show view ON student_17.* TO 'student_17'@'%';
GRANT Trigger ON student_17.* TO 'student_17'@'%';
GRANT Update ON student_17.* TO 'student_17'@'%';
GRANT Alter routine ON student_17.* TO 'student_17'@'%';
GRANT Create routine ON student_17.* TO 'student_17'@'%';
GRANT Create temporary tables ON student_17.* TO 'student_17'@'%';
GRANT Execute ON student_17.* TO 'student_17'@'%';
GRANT Lock tables ON student_17.* TO 'student_17'@'%';

CREATE USER 'student_18'@'%';
ALTER USER 'student_18'@'%'
IDENTIFIED BY 'student_18' ;
GRANT Alter ON student_18.* TO 'student_18'@'%';
GRANT Create ON student_18.* TO 'student_18'@'%';
GRANT Create view ON student_18.* TO 'student_18'@'%';
GRANT Delete ON student_18.* TO 'student_18'@'%';
GRANT Drop ON student_18.* TO 'student_18'@'%';
GRANT Grant option ON student_18.* TO 'student_18'@'%';
GRANT Index ON student_18.* TO 'student_18'@'%';
GRANT Insert ON student_18.* TO 'student_18'@'%';
GRANT References ON student_18.* TO 'student_18'@'%';
GRANT Select ON student_18.* TO 'student_18'@'%';
GRANT Show view ON student_18.* TO 'student_18'@'%';
GRANT Trigger ON student_18.* TO 'student_18'@'%';
GRANT Update ON student_18.* TO 'student_18'@'%';
GRANT Alter routine ON student_18.* TO 'student_18'@'%';
GRANT Create routine ON student_18.* TO 'student_18'@'%';
GRANT Create temporary tables ON student_18.* TO 'student_18'@'%';
GRANT Execute ON student_18.* TO 'student_18'@'%';
GRANT Lock tables ON student_18.* TO 'student_18'@'%';

CREATE USER 'student_19'@'%';
ALTER USER 'student_19'@'%'
IDENTIFIED BY 'student_19' ;
GRANT Alter ON student_19.* TO 'student_19'@'%';
GRANT Create ON student_19.* TO 'student_19'@'%';
GRANT Create view ON student_19.* TO 'student_19'@'%';
GRANT Delete ON student_19.* TO 'student_19'@'%';
GRANT Drop ON student_19.* TO 'student_19'@'%';
GRANT Grant option ON student_19.* TO 'student_19'@'%';
GRANT Index ON student_19.* TO 'student_19'@'%';
GRANT Insert ON student_19.* TO 'student_19'@'%';
GRANT References ON student_19.* TO 'student_19'@'%';
GRANT Select ON student_19.* TO 'student_19'@'%';
GRANT Show view ON student_19.* TO 'student_19'@'%';
GRANT Trigger ON student_19.* TO 'student_19'@'%';
GRANT Update ON student_19.* TO 'student_19'@'%';
GRANT Alter routine ON student_19.* TO 'student_19'@'%';
GRANT Create routine ON student_19.* TO 'student_19'@'%';
GRANT Create temporary tables ON student_19.* TO 'student_19'@'%';
GRANT Execute ON student_19.* TO 'student_19'@'%';
GRANT Lock tables ON student_19.* TO 'student_19'@'%';

CREATE USER 'student_20'@'%';
ALTER USER 'student_20'@'%'
IDENTIFIED BY 'student_20' ;
GRANT Alter ON student_20.* TO 'student_20'@'%';
GRANT Create ON student_20.* TO 'student_20'@'%';
GRANT Create view ON student_20.* TO 'student_20'@'%';
GRANT Delete ON student_20.* TO 'student_20'@'%';
GRANT Drop ON student_20.* TO 'student_20'@'%';
GRANT Grant option ON student_20.* TO 'student_20'@'%';
GRANT Index ON student_20.* TO 'student_20'@'%';
GRANT Insert ON student_20.* TO 'student_20'@'%';
GRANT References ON student_20.* TO 'student_20'@'%';
GRANT Select ON student_20.* TO 'student_20'@'%';
GRANT Show view ON student_20.* TO 'student_20'@'%';
GRANT Trigger ON student_20.* TO 'student_20'@'%';
GRANT Update ON student_20.* TO 'student_20'@'%';
GRANT Alter routine ON student_20.* TO 'student_20'@'%';
GRANT Create routine ON student_20.* TO 'student_20'@'%';
GRANT Create temporary tables ON student_20.* TO 'student_20'@'%';
GRANT Execute ON student_20.* TO 'student_20'@'%';
GRANT Lock tables ON student_20.* TO 'student_20'@'%';

CREATE USER 'student_21'@'%';
ALTER USER 'student_21'@'%'
IDENTIFIED BY 'student_21' ;
GRANT Alter ON student_21.* TO 'student_21'@'%';
GRANT Create ON student_21.* TO 'student_21'@'%';
GRANT Create view ON student_21.* TO 'student_21'@'%';
GRANT Delete ON student_21.* TO 'student_21'@'%';
GRANT Drop ON student_21.* TO 'student_21'@'%';
GRANT Grant option ON student_21.* TO 'student_21'@'%';
GRANT Index ON student_21.* TO 'student_21'@'%';
GRANT Insert ON student_21.* TO 'student_21'@'%';
GRANT References ON student_21.* TO 'student_21'@'%';
GRANT Select ON student_21.* TO 'student_21'@'%';
GRANT Show view ON student_21.* TO 'student_21'@'%';
GRANT Trigger ON student_21.* TO 'student_21'@'%';
GRANT Update ON student_21.* TO 'student_21'@'%';
GRANT Alter routine ON student_21.* TO 'student_21'@'%';
GRANT Create routine ON student_21.* TO 'student_21'@'%';
GRANT Create temporary tables ON student_21.* TO 'student_21'@'%';
GRANT Execute ON student_21.* TO 'student_21'@'%';
GRANT Lock tables ON student_21.* TO 'student_21'@'%';

CREATE USER 'student_22'@'%';
ALTER USER 'student_22'@'%'
IDENTIFIED BY 'student_22' ;
GRANT Alter ON student_22.* TO 'student_22'@'%';
GRANT Create ON student_22.* TO 'student_22'@'%';
GRANT Create view ON student_22.* TO 'student_22'@'%';
GRANT Delete ON student_22.* TO 'student_22'@'%';
GRANT Drop ON student_22.* TO 'student_22'@'%';
GRANT Grant option ON student_22.* TO 'student_22'@'%';
GRANT Index ON student_22.* TO 'student_22'@'%';
GRANT Insert ON student_22.* TO 'student_22'@'%';
GRANT References ON student_22.* TO 'student_22'@'%';
GRANT Select ON student_22.* TO 'student_22'@'%';
GRANT Show view ON student_22.* TO 'student_22'@'%';
GRANT Trigger ON student_22.* TO 'student_22'@'%';
GRANT Update ON student_22.* TO 'student_22'@'%';
GRANT Alter routine ON student_22.* TO 'student_22'@'%';
GRANT Create routine ON student_22.* TO 'student_22'@'%';
GRANT Create temporary tables ON student_22.* TO 'student_22'@'%';
GRANT Execute ON student_22.* TO 'student_22'@'%';
GRANT Lock tables ON student_22.* TO 'student_22'@'%';

CREATE USER 'student_23'@'%';
ALTER USER 'student_23'@'%'
IDENTIFIED BY 'student_23' ;
GRANT Alter ON student_23.* TO 'student_23'@'%';
GRANT Create ON student_23.* TO 'student_23'@'%';
GRANT Create view ON student_23.* TO 'student_23'@'%';
GRANT Delete ON student_23.* TO 'student_23'@'%';
GRANT Drop ON student_23.* TO 'student_23'@'%';
GRANT Grant option ON student_23.* TO 'student_23'@'%';
GRANT Index ON student_23.* TO 'student_23'@'%';
GRANT Insert ON student_23.* TO 'student_23'@'%';
GRANT References ON student_23.* TO 'student_23'@'%';
GRANT Select ON student_23.* TO 'student_23'@'%';
GRANT Show view ON student_23.* TO 'student_23'@'%';
GRANT Trigger ON student_23.* TO 'student_23'@'%';
GRANT Update ON student_23.* TO 'student_23'@'%';
GRANT Alter routine ON student_23.* TO 'student_23'@'%';
GRANT Create routine ON student_23.* TO 'student_23'@'%';
GRANT Create temporary tables ON student_23.* TO 'student_23'@'%';
GRANT Execute ON student_23.* TO 'student_23'@'%';
GRANT Lock tables ON student_23.* TO 'student_23'@'%';

CREATE USER 'student_24'@'%';
ALTER USER 'student_24'@'%'
IDENTIFIED BY 'student_24' ;
GRANT Alter ON student_24.* TO 'student_24'@'%';
GRANT Create ON student_24.* TO 'student_24'@'%';
GRANT Create view ON student_24.* TO 'student_24'@'%';
GRANT Delete ON student_24.* TO 'student_24'@'%';
GRANT Drop ON student_24.* TO 'student_24'@'%';
GRANT Grant option ON student_24.* TO 'student_24'@'%';
GRANT Index ON student_24.* TO 'student_24'@'%';
GRANT Insert ON student_24.* TO 'student_24'@'%';
GRANT References ON student_24.* TO 'student_24'@'%';
GRANT Select ON student_24.* TO 'student_24'@'%';
GRANT Show view ON student_24.* TO 'student_24'@'%';
GRANT Trigger ON student_24.* TO 'student_24'@'%';
GRANT Update ON student_24.* TO 'student_24'@'%';
GRANT Alter routine ON student_24.* TO 'student_24'@'%';
GRANT Create routine ON student_24.* TO 'student_24'@'%';
GRANT Create temporary tables ON student_24.* TO 'student_24'@'%';
GRANT Execute ON student_24.* TO 'student_24'@'%';
GRANT Lock tables ON student_24.* TO 'student_24'@'%';

CREATE USER 'student_25'@'%';
ALTER USER 'student_25'@'%'
IDENTIFIED BY 'student_25' ;
GRANT Alter ON student_25.* TO 'student_25'@'%';
GRANT Create ON student_25.* TO 'student_25'@'%';
GRANT Create view ON student_25.* TO 'student_25'@'%';
GRANT Delete ON student_25.* TO 'student_25'@'%';
GRANT Drop ON student_25.* TO 'student_25'@'%';
GRANT Grant option ON student_25.* TO 'student_25'@'%';
GRANT Index ON student_25.* TO 'student_25'@'%';
GRANT Insert ON student_25.* TO 'student_25'@'%';
GRANT References ON student_25.* TO 'student_25'@'%';
GRANT Select ON student_25.* TO 'student_25'@'%';
GRANT Show view ON student_25.* TO 'student_25'@'%';
GRANT Trigger ON student_25.* TO 'student_25'@'%';
GRANT Update ON student_25.* TO 'student_25'@'%';
GRANT Alter routine ON student_25.* TO 'student_25'@'%';
GRANT Create routine ON student_25.* TO 'student_25'@'%';
GRANT Create temporary tables ON student_25.* TO 'student_25'@'%';
GRANT Execute ON student_25.* TO 'student_25'@'%';
GRANT Lock tables ON student_25.* TO 'student_25'@'%';

CREATE USER 'student_26'@'%';
ALTER USER 'student_26'@'%'
IDENTIFIED BY 'student_26' ;
GRANT Alter ON student_26.* TO 'student_26'@'%';
GRANT Create ON student_26.* TO 'student_26'@'%';
GRANT Create view ON student_26.* TO 'student_26'@'%';
GRANT Delete ON student_26.* TO 'student_26'@'%';
GRANT Drop ON student_26.* TO 'student_26'@'%';
GRANT Grant option ON student_26.* TO 'student_26'@'%';
GRANT Index ON student_26.* TO 'student_26'@'%';
GRANT Insert ON student_26.* TO 'student_26'@'%';
GRANT References ON student_26.* TO 'student_26'@'%';
GRANT Select ON student_26.* TO 'student_26'@'%';
GRANT Show view ON student_26.* TO 'student_26'@'%';
GRANT Trigger ON student_26.* TO 'student_26'@'%';
GRANT Update ON student_26.* TO 'student_26'@'%';
GRANT Alter routine ON student_26.* TO 'student_26'@'%';
GRANT Create routine ON student_26.* TO 'student_26'@'%';
GRANT Create temporary tables ON student_26.* TO 'student_26'@'%';
GRANT Execute ON student_26.* TO 'student_26'@'%';
GRANT Lock tables ON student_26.* TO 'student_26'@'%';

CREATE USER 'student_27'@'%';
ALTER USER 'student_27'@'%'
IDENTIFIED BY 'student_27' ;
GRANT Alter ON student_27.* TO 'student_27'@'%';
GRANT Create ON student_27.* TO 'student_27'@'%';
GRANT Create view ON student_27.* TO 'student_27'@'%';
GRANT Delete ON student_27.* TO 'student_27'@'%';
GRANT Drop ON student_27.* TO 'student_27'@'%';
GRANT Grant option ON student_27.* TO 'student_27'@'%';
GRANT Index ON student_27.* TO 'student_27'@'%';
GRANT Insert ON student_27.* TO 'student_27'@'%';
GRANT References ON student_27.* TO 'student_27'@'%';
GRANT Select ON student_27.* TO 'student_27'@'%';
GRANT Show view ON student_27.* TO 'student_27'@'%';
GRANT Trigger ON student_27.* TO 'student_27'@'%';
GRANT Update ON student_27.* TO 'student_27'@'%';
GRANT Alter routine ON student_27.* TO 'student_27'@'%';
GRANT Create routine ON student_27.* TO 'student_27'@'%';
GRANT Create temporary tables ON student_27.* TO 'student_27'@'%';
GRANT Execute ON student_27.* TO 'student_27'@'%';
GRANT Lock tables ON student_27.* TO 'student_27'@'%';

CREATE USER 'student_28'@'%';
ALTER USER 'student_28'@'%'
IDENTIFIED BY 'student_28' ;
GRANT Alter ON student_28.* TO 'student_28'@'%';
GRANT Create ON student_28.* TO 'student_28'@'%';
GRANT Create view ON student_28.* TO 'student_28'@'%';
GRANT Delete ON student_28.* TO 'student_28'@'%';
GRANT Drop ON student_28.* TO 'student_28'@'%';
GRANT Grant option ON student_28.* TO 'student_28'@'%';
GRANT Index ON student_28.* TO 'student_28'@'%';
GRANT Insert ON student_28.* TO 'student_28'@'%';
GRANT References ON student_28.* TO 'student_28'@'%';
GRANT Select ON student_28.* TO 'student_28'@'%';
GRANT Show view ON student_28.* TO 'student_28'@'%';
GRANT Trigger ON student_28.* TO 'student_28'@'%';
GRANT Update ON student_28.* TO 'student_28'@'%';
GRANT Alter routine ON student_28.* TO 'student_28'@'%';
GRANT Create routine ON student_28.* TO 'student_28'@'%';
GRANT Create temporary tables ON student_28.* TO 'student_28'@'%';
GRANT Execute ON student_28.* TO 'student_28'@'%';
GRANT Lock tables ON student_28.* TO 'student_28'@'%';

CREATE USER 'student_29'@'%';
ALTER USER 'student_29'@'%'
IDENTIFIED BY 'student_29' ;
GRANT Alter ON student_29.* TO 'student_29'@'%';
GRANT Create ON student_29.* TO 'student_29'@'%';
GRANT Create view ON student_29.* TO 'student_29'@'%';
GRANT Delete ON student_29.* TO 'student_29'@'%';
GRANT Drop ON student_29.* TO 'student_29'@'%';
GRANT Grant option ON student_29.* TO 'student_29'@'%';
GRANT Index ON student_29.* TO 'student_29'@'%';
GRANT Insert ON student_29.* TO 'student_29'@'%';
GRANT References ON student_29.* TO 'student_29'@'%';
GRANT Select ON student_29.* TO 'student_29'@'%';
GRANT Show view ON student_29.* TO 'student_29'@'%';
GRANT Trigger ON student_29.* TO 'student_29'@'%';
GRANT Update ON student_29.* TO 'student_29'@'%';
GRANT Alter routine ON student_29.* TO 'student_29'@'%';
GRANT Create routine ON student_29.* TO 'student_29'@'%';
GRANT Create temporary tables ON student_29.* TO 'student_29'@'%';
GRANT Execute ON student_29.* TO 'student_29'@'%';
GRANT Lock tables ON student_29.* TO 'student_29'@'%';

CREATE USER 'student_30'@'%';
ALTER USER 'student_30'@'%'
IDENTIFIED BY 'student_30' ;
GRANT Alter ON student_30.* TO 'student_30'@'%';
GRANT Create ON student_30.* TO 'student_30'@'%';
GRANT Create view ON student_30.* TO 'student_30'@'%';
GRANT Delete ON student_30.* TO 'student_30'@'%';
GRANT Drop ON student_30.* TO 'student_30'@'%';
GRANT Grant option ON student_30.* TO 'student_30'@'%';
GRANT Index ON student_30.* TO 'student_30'@'%';
GRANT Insert ON student_30.* TO 'student_30'@'%';
GRANT References ON student_30.* TO 'student_30'@'%';
GRANT Select ON student_30.* TO 'student_30'@'%';
GRANT Show view ON student_30.* TO 'student_30'@'%';
GRANT Trigger ON student_30.* TO 'student_30'@'%';
GRANT Update ON student_30.* TO 'student_30'@'%';
GRANT Alter routine ON student_30.* TO 'student_30'@'%';
GRANT Create routine ON student_30.* TO 'student_30'@'%';
GRANT Create temporary tables ON student_30.* TO 'student_30'@'%';
GRANT Execute ON student_30.* TO 'student_30'@'%';
GRANT Lock tables ON student_30.* TO 'student_30'@'%';

CREATE USER 'student_31'@'%';
ALTER USER 'student_31'@'%'
IDENTIFIED BY 'student_31' ;
GRANT Alter ON student_31.* TO 'student_31'@'%';
GRANT Create ON student_31.* TO 'student_31'@'%';
GRANT Create view ON student_31.* TO 'student_31'@'%';
GRANT Delete ON student_31.* TO 'student_31'@'%';
GRANT Drop ON student_31.* TO 'student_31'@'%';
GRANT Grant option ON student_31.* TO 'student_31'@'%';
GRANT Index ON student_31.* TO 'student_31'@'%';
GRANT Insert ON student_31.* TO 'student_31'@'%';
GRANT References ON student_31.* TO 'student_31'@'%';
GRANT Select ON student_31.* TO 'student_31'@'%';
GRANT Show view ON student_31.* TO 'student_31'@'%';
GRANT Trigger ON student_31.* TO 'student_31'@'%';
GRANT Update ON student_31.* TO 'student_31'@'%';
GRANT Alter routine ON student_31.* TO 'student_31'@'%';
GRANT Create routine ON student_31.* TO 'student_31'@'%';
GRANT Create temporary tables ON student_31.* TO 'student_31'@'%';
GRANT Execute ON student_31.* TO 'student_31'@'%';
GRANT Lock tables ON student_31.* TO 'student_31'@'%';

CREATE USER 'student_32'@'%';
ALTER USER 'student_32'@'%'
IDENTIFIED BY 'student_32' ;
GRANT Alter ON student_32.* TO 'student_32'@'%';
GRANT Create ON student_32.* TO 'student_32'@'%';
GRANT Create view ON student_32.* TO 'student_32'@'%';
GRANT Delete ON student_32.* TO 'student_32'@'%';
GRANT Drop ON student_32.* TO 'student_32'@'%';
GRANT Grant option ON student_32.* TO 'student_32'@'%';
GRANT Index ON student_32.* TO 'student_32'@'%';
GRANT Insert ON student_32.* TO 'student_32'@'%';
GRANT References ON student_32.* TO 'student_32'@'%';
GRANT Select ON student_32.* TO 'student_32'@'%';
GRANT Show view ON student_32.* TO 'student_32'@'%';
GRANT Trigger ON student_32.* TO 'student_32'@'%';
GRANT Update ON student_32.* TO 'student_32'@'%';
GRANT Alter routine ON student_32.* TO 'student_32'@'%';
GRANT Create routine ON student_32.* TO 'student_32'@'%';
GRANT Create temporary tables ON student_32.* TO 'student_32'@'%';
GRANT Execute ON student_32.* TO 'student_32'@'%';
GRANT Lock tables ON student_32.* TO 'student_32'@'%';

CREATE USER 'student_33'@'%';
ALTER USER 'student_33'@'%'
IDENTIFIED BY 'student_33' ;
GRANT Alter ON student_33.* TO 'student_33'@'%';
GRANT Create ON student_33.* TO 'student_33'@'%';
GRANT Create view ON student_33.* TO 'student_33'@'%';
GRANT Delete ON student_33.* TO 'student_33'@'%';
GRANT Drop ON student_33.* TO 'student_33'@'%';
GRANT Grant option ON student_33.* TO 'student_33'@'%';
GRANT Index ON student_33.* TO 'student_33'@'%';
GRANT Insert ON student_33.* TO 'student_33'@'%';
GRANT References ON student_33.* TO 'student_33'@'%';
GRANT Select ON student_33.* TO 'student_33'@'%';
GRANT Show view ON student_33.* TO 'student_33'@'%';
GRANT Trigger ON student_33.* TO 'student_33'@'%';
GRANT Update ON student_33.* TO 'student_33'@'%';
GRANT Alter routine ON student_33.* TO 'student_33'@'%';
GRANT Create routine ON student_33.* TO 'student_33'@'%';
GRANT Create temporary tables ON student_33.* TO 'student_33'@'%';
GRANT Execute ON student_33.* TO 'student_33'@'%';
GRANT Lock tables ON student_33.* TO 'student_33'@'%';

CREATE USER 'student_34'@'%';
ALTER USER 'student_34'@'%'
IDENTIFIED BY 'student_34' ;
GRANT Alter ON student_34.* TO 'student_34'@'%';
GRANT Create ON student_34.* TO 'student_34'@'%';
GRANT Create view ON student_34.* TO 'student_34'@'%';
GRANT Delete ON student_34.* TO 'student_34'@'%';
GRANT Drop ON student_34.* TO 'student_34'@'%';
GRANT Grant option ON student_34.* TO 'student_34'@'%';
GRANT Index ON student_34.* TO 'student_34'@'%';
GRANT Insert ON student_34.* TO 'student_34'@'%';
GRANT References ON student_34.* TO 'student_34'@'%';
GRANT Select ON student_34.* TO 'student_34'@'%';
GRANT Show view ON student_34.* TO 'student_34'@'%';
GRANT Trigger ON student_34.* TO 'student_34'@'%';
GRANT Update ON student_34.* TO 'student_34'@'%';
GRANT Alter routine ON student_34.* TO 'student_34'@'%';
GRANT Create routine ON student_34.* TO 'student_34'@'%';
GRANT Create temporary tables ON student_34.* TO 'student_34'@'%';
GRANT Execute ON student_34.* TO 'student_34'@'%';
GRANT Lock tables ON student_34.* TO 'student_34'@'%';

CREATE USER 'student_35'@'%';
ALTER USER 'student_35'@'%'
IDENTIFIED BY 'student_35' ;
GRANT Alter ON student_35.* TO 'student_35'@'%';
GRANT Create ON student_35.* TO 'student_35'@'%';
GRANT Create view ON student_35.* TO 'student_35'@'%';
GRANT Delete ON student_35.* TO 'student_35'@'%';
GRANT Drop ON student_35.* TO 'student_35'@'%';
GRANT Grant option ON student_35.* TO 'student_35'@'%';
GRANT Index ON student_35.* TO 'student_35'@'%';
GRANT Insert ON student_35.* TO 'student_35'@'%';
GRANT References ON student_35.* TO 'student_35'@'%';
GRANT Select ON student_35.* TO 'student_35'@'%';
GRANT Show view ON student_35.* TO 'student_35'@'%';
GRANT Trigger ON student_35.* TO 'student_35'@'%';
GRANT Update ON student_35.* TO 'student_35'@'%';
GRANT Alter routine ON student_35.* TO 'student_35'@'%';
GRANT Create routine ON student_35.* TO 'student_35'@'%';
GRANT Create temporary tables ON student_35.* TO 'student_35'@'%';
GRANT Execute ON student_35.* TO 'student_35'@'%';
GRANT Lock tables ON student_35.* TO 'student_35'@'%';

CREATE USER 'student_36'@'%';
ALTER USER 'student_36'@'%'
IDENTIFIED BY 'student_36' ;
GRANT Alter ON student_36.* TO 'student_36'@'%';
GRANT Create ON student_36.* TO 'student_36'@'%';
GRANT Create view ON student_36.* TO 'student_36'@'%';
GRANT Delete ON student_36.* TO 'student_36'@'%';
GRANT Drop ON student_36.* TO 'student_36'@'%';
GRANT Grant option ON student_36.* TO 'student_36'@'%';
GRANT Index ON student_36.* TO 'student_36'@'%';
GRANT Insert ON student_36.* TO 'student_36'@'%';
GRANT References ON student_36.* TO 'student_36'@'%';
GRANT Select ON student_36.* TO 'student_36'@'%';
GRANT Show view ON student_36.* TO 'student_36'@'%';
GRANT Trigger ON student_36.* TO 'student_36'@'%';
GRANT Update ON student_36.* TO 'student_36'@'%';
GRANT Alter routine ON student_36.* TO 'student_36'@'%';
GRANT Create routine ON student_36.* TO 'student_36'@'%';
GRANT Create temporary tables ON student_36.* TO 'student_36'@'%';
GRANT Execute ON student_36.* TO 'student_36'@'%';
GRANT Lock tables ON student_36.* TO 'student_36'@'%';

CREATE USER 'student_37'@'%';
ALTER USER 'student_37'@'%'
IDENTIFIED BY 'student_37' ;
GRANT Alter ON student_37.* TO 'student_37'@'%';
GRANT Create ON student_37.* TO 'student_37'@'%';
GRANT Create view ON student_37.* TO 'student_37'@'%';
GRANT Delete ON student_37.* TO 'student_37'@'%';
GRANT Drop ON student_37.* TO 'student_37'@'%';
GRANT Grant option ON student_37.* TO 'student_37'@'%';
GRANT Index ON student_37.* TO 'student_37'@'%';
GRANT Insert ON student_37.* TO 'student_37'@'%';
GRANT References ON student_37.* TO 'student_37'@'%';
GRANT Select ON student_37.* TO 'student_37'@'%';
GRANT Show view ON student_37.* TO 'student_37'@'%';
GRANT Trigger ON student_37.* TO 'student_37'@'%';
GRANT Update ON student_37.* TO 'student_37'@'%';
GRANT Alter routine ON student_37.* TO 'student_37'@'%';
GRANT Create routine ON student_37.* TO 'student_37'@'%';
GRANT Create temporary tables ON student_37.* TO 'student_37'@'%';
GRANT Execute ON student_37.* TO 'student_37'@'%';
GRANT Lock tables ON student_37.* TO 'student_37'@'%';

CREATE USER 'student_38'@'%';
ALTER USER 'student_38'@'%'
IDENTIFIED BY 'student_38' ;
GRANT Alter ON student_38.* TO 'student_38'@'%';
GRANT Create ON student_38.* TO 'student_38'@'%';
GRANT Create view ON student_38.* TO 'student_38'@'%';
GRANT Delete ON student_38.* TO 'student_38'@'%';
GRANT Drop ON student_38.* TO 'student_38'@'%';
GRANT Grant option ON student_38.* TO 'student_38'@'%';
GRANT Index ON student_38.* TO 'student_38'@'%';
GRANT Insert ON student_38.* TO 'student_38'@'%';
GRANT References ON student_38.* TO 'student_38'@'%';
GRANT Select ON student_38.* TO 'student_38'@'%';
GRANT Show view ON student_38.* TO 'student_38'@'%';
GRANT Trigger ON student_38.* TO 'student_38'@'%';
GRANT Update ON student_38.* TO 'student_38'@'%';
GRANT Alter routine ON student_38.* TO 'student_38'@'%';
GRANT Create routine ON student_38.* TO 'student_38'@'%';
GRANT Create temporary tables ON student_38.* TO 'student_38'@'%';
GRANT Execute ON student_38.* TO 'student_38'@'%';
GRANT Lock tables ON student_38.* TO 'student_38'@'%';

CREATE USER 'student_39'@'%';
ALTER USER 'student_39'@'%'
IDENTIFIED BY 'student_39' ;
GRANT Alter ON student_39.* TO 'student_39'@'%';
GRANT Create ON student_39.* TO 'student_39'@'%';
GRANT Create view ON student_39.* TO 'student_39'@'%';
GRANT Delete ON student_39.* TO 'student_39'@'%';
GRANT Drop ON student_39.* TO 'student_39'@'%';
GRANT Grant option ON student_39.* TO 'student_39'@'%';
GRANT Index ON student_39.* TO 'student_39'@'%';
GRANT Insert ON student_39.* TO 'student_39'@'%';
GRANT References ON student_39.* TO 'student_39'@'%';
GRANT Select ON student_39.* TO 'student_39'@'%';
GRANT Show view ON student_39.* TO 'student_39'@'%';
GRANT Trigger ON student_39.* TO 'student_39'@'%';
GRANT Update ON student_39.* TO 'student_39'@'%';
GRANT Alter routine ON student_39.* TO 'student_39'@'%';
GRANT Create routine ON student_39.* TO 'student_39'@'%';
GRANT Create temporary tables ON student_39.* TO 'student_39'@'%';
GRANT Execute ON student_39.* TO 'student_39'@'%';
GRANT Lock tables ON student_39.* TO 'student_39'@'%';

CREATE USER 'student_40'@'%';
ALTER USER 'student_40'@'%'
IDENTIFIED BY 'student_40' ;
GRANT Alter ON student_40.* TO 'student_40'@'%';
GRANT Create ON student_40.* TO 'student_40'@'%';
GRANT Create view ON student_40.* TO 'student_40'@'%';
GRANT Delete ON student_40.* TO 'student_40'@'%';
GRANT Drop ON student_40.* TO 'student_40'@'%';
GRANT Grant option ON student_40.* TO 'student_40'@'%';
GRANT Index ON student_40.* TO 'student_40'@'%';
GRANT Insert ON student_40.* TO 'student_40'@'%';
GRANT References ON student_40.* TO 'student_40'@'%';
GRANT Select ON student_40.* TO 'student_40'@'%';
GRANT Show view ON student_40.* TO 'student_40'@'%';
GRANT Trigger ON student_40.* TO 'student_40'@'%';
GRANT Update ON student_40.* TO 'student_40'@'%';
GRANT Alter routine ON student_40.* TO 'student_40'@'%';
GRANT Create routine ON student_40.* TO 'student_40'@'%';
GRANT Create temporary tables ON student_40.* TO 'student_40'@'%';
GRANT Execute ON student_40.* TO 'student_40'@'%';
GRANT Lock tables ON student_40.* TO 'student_40'@'%';

CREATE USER 'student_41'@'%';
ALTER USER 'student_41'@'%'
IDENTIFIED BY 'student_41' ;
GRANT Alter ON student_41.* TO 'student_41'@'%';
GRANT Create ON student_41.* TO 'student_41'@'%';
GRANT Create view ON student_41.* TO 'student_41'@'%';
GRANT Delete ON student_41.* TO 'student_41'@'%';
GRANT Drop ON student_41.* TO 'student_41'@'%';
GRANT Grant option ON student_41.* TO 'student_41'@'%';
GRANT Index ON student_41.* TO 'student_41'@'%';
GRANT Insert ON student_41.* TO 'student_41'@'%';
GRANT References ON student_41.* TO 'student_41'@'%';
GRANT Select ON student_41.* TO 'student_41'@'%';
GRANT Show view ON student_41.* TO 'student_41'@'%';
GRANT Trigger ON student_41.* TO 'student_41'@'%';
GRANT Update ON student_41.* TO 'student_41'@'%';
GRANT Alter routine ON student_41.* TO 'student_41'@'%';
GRANT Create routine ON student_41.* TO 'student_41'@'%';
GRANT Create temporary tables ON student_41.* TO 'student_41'@'%';
GRANT Execute ON student_41.* TO 'student_41'@'%';
GRANT Lock tables ON student_41.* TO 'student_41'@'%';

CREATE USER 'student_42'@'%';
ALTER USER 'student_42'@'%'
IDENTIFIED BY 'student_42' ;
GRANT Alter ON student_42.* TO 'student_42'@'%';
GRANT Create ON student_42.* TO 'student_42'@'%';
GRANT Create view ON student_42.* TO 'student_42'@'%';
GRANT Delete ON student_42.* TO 'student_42'@'%';
GRANT Drop ON student_42.* TO 'student_42'@'%';
GRANT Grant option ON student_42.* TO 'student_42'@'%';
GRANT Index ON student_42.* TO 'student_42'@'%';
GRANT Insert ON student_42.* TO 'student_42'@'%';
GRANT References ON student_42.* TO 'student_42'@'%';
GRANT Select ON student_42.* TO 'student_42'@'%';
GRANT Show view ON student_42.* TO 'student_42'@'%';
GRANT Trigger ON student_42.* TO 'student_42'@'%';
GRANT Update ON student_42.* TO 'student_42'@'%';
GRANT Alter routine ON student_42.* TO 'student_42'@'%';
GRANT Create routine ON student_42.* TO 'student_42'@'%';
GRANT Create temporary tables ON student_42.* TO 'student_42'@'%';
GRANT Execute ON student_42.* TO 'student_42'@'%';
GRANT Lock tables ON student_42.* TO 'student_42'@'%';

CREATE USER 'student_43'@'%';
ALTER USER 'student_43'@'%'
IDENTIFIED BY 'student_43' ;
GRANT Alter ON student_43.* TO 'student_43'@'%';
GRANT Create ON student_43.* TO 'student_43'@'%';
GRANT Create view ON student_43.* TO 'student_43'@'%';
GRANT Delete ON student_43.* TO 'student_43'@'%';
GRANT Drop ON student_43.* TO 'student_43'@'%';
GRANT Grant option ON student_43.* TO 'student_43'@'%';
GRANT Index ON student_43.* TO 'student_43'@'%';
GRANT Insert ON student_43.* TO 'student_43'@'%';
GRANT References ON student_43.* TO 'student_43'@'%';
GRANT Select ON student_43.* TO 'student_43'@'%';
GRANT Show view ON student_43.* TO 'student_43'@'%';
GRANT Trigger ON student_43.* TO 'student_43'@'%';
GRANT Update ON student_43.* TO 'student_43'@'%';
GRANT Alter routine ON student_43.* TO 'student_43'@'%';
GRANT Create routine ON student_43.* TO 'student_43'@'%';
GRANT Create temporary tables ON student_43.* TO 'student_43'@'%';
GRANT Execute ON student_43.* TO 'student_43'@'%';
GRANT Lock tables ON student_43.* TO 'student_43'@'%';

CREATE USER 'student_44'@'%';
ALTER USER 'student_44'@'%'
IDENTIFIED BY 'student_44' ;
GRANT Alter ON student_44.* TO 'student_44'@'%';
GRANT Create ON student_44.* TO 'student_44'@'%';
GRANT Create view ON student_44.* TO 'student_44'@'%';
GRANT Delete ON student_44.* TO 'student_44'@'%';
GRANT Drop ON student_44.* TO 'student_44'@'%';
GRANT Grant option ON student_44.* TO 'student_44'@'%';
GRANT Index ON student_44.* TO 'student_44'@'%';
GRANT Insert ON student_44.* TO 'student_44'@'%';
GRANT References ON student_44.* TO 'student_44'@'%';
GRANT Select ON student_44.* TO 'student_44'@'%';
GRANT Show view ON student_44.* TO 'student_44'@'%';
GRANT Trigger ON student_44.* TO 'student_44'@'%';
GRANT Update ON student_44.* TO 'student_44'@'%';
GRANT Alter routine ON student_44.* TO 'student_44'@'%';
GRANT Create routine ON student_44.* TO 'student_44'@'%';
GRANT Create temporary tables ON student_44.* TO 'student_44'@'%';
GRANT Execute ON student_44.* TO 'student_44'@'%';
GRANT Lock tables ON student_44.* TO 'student_44'@'%';

CREATE USER 'student_45'@'%';
ALTER USER 'student_45'@'%'
IDENTIFIED BY 'student_45' ;
GRANT Alter ON student_45.* TO 'student_45'@'%';
GRANT Create ON student_45.* TO 'student_45'@'%';
GRANT Create view ON student_45.* TO 'student_45'@'%';
GRANT Delete ON student_45.* TO 'student_45'@'%';
GRANT Drop ON student_45.* TO 'student_45'@'%';
GRANT Grant option ON student_45.* TO 'student_45'@'%';
GRANT Index ON student_45.* TO 'student_45'@'%';
GRANT Insert ON student_45.* TO 'student_45'@'%';
GRANT References ON student_45.* TO 'student_45'@'%';
GRANT Select ON student_45.* TO 'student_45'@'%';
GRANT Show view ON student_45.* TO 'student_45'@'%';
GRANT Trigger ON student_45.* TO 'student_45'@'%';
GRANT Update ON student_45.* TO 'student_45'@'%';
GRANT Alter routine ON student_45.* TO 'student_45'@'%';
GRANT Create routine ON student_45.* TO 'student_45'@'%';
GRANT Create temporary tables ON student_45.* TO 'student_45'@'%';
GRANT Execute ON student_45.* TO 'student_45'@'%';
GRANT Lock tables ON student_45.* TO 'student_45'@'%';

CREATE USER 'student_46'@'%';
ALTER USER 'student_46'@'%'
IDENTIFIED BY 'student_46' ;
GRANT Alter ON student_46.* TO 'student_46'@'%';
GRANT Create ON student_46.* TO 'student_46'@'%';
GRANT Create view ON student_46.* TO 'student_46'@'%';
GRANT Delete ON student_46.* TO 'student_46'@'%';
GRANT Drop ON student_46.* TO 'student_46'@'%';
GRANT Grant option ON student_46.* TO 'student_46'@'%';
GRANT Index ON student_46.* TO 'student_46'@'%';
GRANT Insert ON student_46.* TO 'student_46'@'%';
GRANT References ON student_46.* TO 'student_46'@'%';
GRANT Select ON student_46.* TO 'student_46'@'%';
GRANT Show view ON student_46.* TO 'student_46'@'%';
GRANT Trigger ON student_46.* TO 'student_46'@'%';
GRANT Update ON student_46.* TO 'student_46'@'%';
GRANT Alter routine ON student_46.* TO 'student_46'@'%';
GRANT Create routine ON student_46.* TO 'student_46'@'%';
GRANT Create temporary tables ON student_46.* TO 'student_46'@'%';
GRANT Execute ON student_46.* TO 'student_46'@'%';
GRANT Lock tables ON student_46.* TO 'student_46'@'%';

CREATE USER 'student_47'@'%';
ALTER USER 'student_47'@'%'
IDENTIFIED BY 'student_47' ;
GRANT Alter ON student_47.* TO 'student_47'@'%';
GRANT Create ON student_47.* TO 'student_47'@'%';
GRANT Create view ON student_47.* TO 'student_47'@'%';
GRANT Delete ON student_47.* TO 'student_47'@'%';
GRANT Drop ON student_47.* TO 'student_47'@'%';
GRANT Grant option ON student_47.* TO 'student_47'@'%';
GRANT Index ON student_47.* TO 'student_47'@'%';
GRANT Insert ON student_47.* TO 'student_47'@'%';
GRANT References ON student_47.* TO 'student_47'@'%';
GRANT Select ON student_47.* TO 'student_47'@'%';
GRANT Show view ON student_47.* TO 'student_47'@'%';
GRANT Trigger ON student_47.* TO 'student_47'@'%';
GRANT Update ON student_47.* TO 'student_47'@'%';
GRANT Alter routine ON student_47.* TO 'student_47'@'%';
GRANT Create routine ON student_47.* TO 'student_47'@'%';
GRANT Create temporary tables ON student_47.* TO 'student_47'@'%';
GRANT Execute ON student_47.* TO 'student_47'@'%';
GRANT Lock tables ON student_47.* TO 'student_47'@'%';

CREATE USER 'student_48'@'%';
ALTER USER 'student_48'@'%'
IDENTIFIED BY 'student_48' ;
GRANT Alter ON student_48.* TO 'student_48'@'%';
GRANT Create ON student_48.* TO 'student_48'@'%';
GRANT Create view ON student_48.* TO 'student_48'@'%';
GRANT Delete ON student_48.* TO 'student_48'@'%';
GRANT Drop ON student_48.* TO 'student_48'@'%';
GRANT Grant option ON student_48.* TO 'student_48'@'%';
GRANT Index ON student_48.* TO 'student_48'@'%';
GRANT Insert ON student_48.* TO 'student_48'@'%';
GRANT References ON student_48.* TO 'student_48'@'%';
GRANT Select ON student_48.* TO 'student_48'@'%';
GRANT Show view ON student_48.* TO 'student_48'@'%';
GRANT Trigger ON student_48.* TO 'student_48'@'%';
GRANT Update ON student_48.* TO 'student_48'@'%';
GRANT Alter routine ON student_48.* TO 'student_48'@'%';
GRANT Create routine ON student_48.* TO 'student_48'@'%';
GRANT Create temporary tables ON student_48.* TO 'student_48'@'%';
GRANT Execute ON student_48.* TO 'student_48'@'%';
GRANT Lock tables ON student_48.* TO 'student_48'@'%';

CREATE USER 'student_49'@'%';
ALTER USER 'student_49'@'%'
IDENTIFIED BY 'student_49' ;
GRANT Alter ON student_49.* TO 'student_49'@'%';
GRANT Create ON student_49.* TO 'student_49'@'%';
GRANT Create view ON student_49.* TO 'student_49'@'%';
GRANT Delete ON student_49.* TO 'student_49'@'%';
GRANT Drop ON student_49.* TO 'student_49'@'%';
GRANT Grant option ON student_49.* TO 'student_49'@'%';
GRANT Index ON student_49.* TO 'student_49'@'%';
GRANT Insert ON student_49.* TO 'student_49'@'%';
GRANT References ON student_49.* TO 'student_49'@'%';
GRANT Select ON student_49.* TO 'student_49'@'%';
GRANT Show view ON student_49.* TO 'student_49'@'%';
GRANT Trigger ON student_49.* TO 'student_49'@'%';
GRANT Update ON student_49.* TO 'student_49'@'%';
GRANT Alter routine ON student_49.* TO 'student_49'@'%';
GRANT Create routine ON student_49.* TO 'student_49'@'%';
GRANT Create temporary tables ON student_49.* TO 'student_49'@'%';
GRANT Execute ON student_49.* TO 'student_49'@'%';
GRANT Lock tables ON student_49.* TO 'student_49'@'%';

CREATE USER 'student_50'@'%';
ALTER USER 'student_50'@'%'
IDENTIFIED BY 'student_50' ;
GRANT Alter ON student_50.* TO 'student_50'@'%';
GRANT Create ON student_50.* TO 'student_50'@'%';
GRANT Create view ON student_50.* TO 'student_50'@'%';
GRANT Delete ON student_50.* TO 'student_50'@'%';
GRANT Drop ON student_50.* TO 'student_50'@'%';
GRANT Grant option ON student_50.* TO 'student_50'@'%';
GRANT Index ON student_50.* TO 'student_50'@'%';
GRANT Insert ON student_50.* TO 'student_50'@'%';
GRANT References ON student_50.* TO 'student_50'@'%';
GRANT Select ON student_50.* TO 'student_50'@'%';
GRANT Show view ON student_50.* TO 'student_50'@'%';
GRANT Trigger ON student_50.* TO 'student_50'@'%';
GRANT Update ON student_50.* TO 'student_50'@'%';
GRANT Alter routine ON student_50.* TO 'student_50'@'%';
GRANT Create routine ON student_50.* TO 'student_50'@'%';
GRANT Create temporary tables ON student_50.* TO 'student_50'@'%';
GRANT Execute ON student_50.* TO 'student_50'@'%';
GRANT Lock tables ON student_50.* TO 'student_50'@'%';

CREATE USER 'student_51'@'%';
ALTER USER 'student_51'@'%'
IDENTIFIED BY 'student_51' ;
GRANT Alter ON student_51.* TO 'student_51'@'%';
GRANT Create ON student_51.* TO 'student_51'@'%';
GRANT Create view ON student_51.* TO 'student_51'@'%';
GRANT Delete ON student_51.* TO 'student_51'@'%';
GRANT Drop ON student_51.* TO 'student_51'@'%';
GRANT Grant option ON student_51.* TO 'student_51'@'%';
GRANT Index ON student_51.* TO 'student_51'@'%';
GRANT Insert ON student_51.* TO 'student_51'@'%';
GRANT References ON student_51.* TO 'student_51'@'%';
GRANT Select ON student_51.* TO 'student_51'@'%';
GRANT Show view ON student_51.* TO 'student_51'@'%';
GRANT Trigger ON student_51.* TO 'student_51'@'%';
GRANT Update ON student_51.* TO 'student_51'@'%';
GRANT Alter routine ON student_51.* TO 'student_51'@'%';
GRANT Create routine ON student_51.* TO 'student_51'@'%';
GRANT Create temporary tables ON student_51.* TO 'student_51'@'%';
GRANT Execute ON student_51.* TO 'student_51'@'%';
GRANT Lock tables ON student_51.* TO 'student_51'@'%';

CREATE USER 'student_52'@'%';
ALTER USER 'student_52'@'%'
IDENTIFIED BY 'student_52' ;
GRANT Alter ON student_52.* TO 'student_52'@'%';
GRANT Create ON student_52.* TO 'student_52'@'%';
GRANT Create view ON student_52.* TO 'student_52'@'%';
GRANT Delete ON student_52.* TO 'student_52'@'%';
GRANT Drop ON student_52.* TO 'student_52'@'%';
GRANT Grant option ON student_52.* TO 'student_52'@'%';
GRANT Index ON student_52.* TO 'student_52'@'%';
GRANT Insert ON student_52.* TO 'student_52'@'%';
GRANT References ON student_52.* TO 'student_52'@'%';
GRANT Select ON student_52.* TO 'student_52'@'%';
GRANT Show view ON student_52.* TO 'student_52'@'%';
GRANT Trigger ON student_52.* TO 'student_52'@'%';
GRANT Update ON student_52.* TO 'student_52'@'%';
GRANT Alter routine ON student_52.* TO 'student_52'@'%';
GRANT Create routine ON student_52.* TO 'student_52'@'%';
GRANT Create temporary tables ON student_52.* TO 'student_52'@'%';
GRANT Execute ON student_52.* TO 'student_52'@'%';
GRANT Lock tables ON student_52.* TO 'student_52'@'%';

CREATE USER 'student_53'@'%';
ALTER USER 'student_53'@'%'
IDENTIFIED BY 'student_53' ;
GRANT Alter ON student_53.* TO 'student_53'@'%';
GRANT Create ON student_53.* TO 'student_53'@'%';
GRANT Create view ON student_53.* TO 'student_53'@'%';
GRANT Delete ON student_53.* TO 'student_53'@'%';
GRANT Drop ON student_53.* TO 'student_53'@'%';
GRANT Grant option ON student_53.* TO 'student_53'@'%';
GRANT Index ON student_53.* TO 'student_53'@'%';
GRANT Insert ON student_53.* TO 'student_53'@'%';
GRANT References ON student_53.* TO 'student_53'@'%';
GRANT Select ON student_53.* TO 'student_53'@'%';
GRANT Show view ON student_53.* TO 'student_53'@'%';
GRANT Trigger ON student_53.* TO 'student_53'@'%';
GRANT Update ON student_53.* TO 'student_53'@'%';
GRANT Alter routine ON student_53.* TO 'student_53'@'%';
GRANT Create routine ON student_53.* TO 'student_53'@'%';
GRANT Create temporary tables ON student_53.* TO 'student_53'@'%';
GRANT Execute ON student_53.* TO 'student_53'@'%';
GRANT Lock tables ON student_53.* TO 'student_53'@'%';

CREATE USER 'student_54'@'%';
ALTER USER 'student_54'@'%'
IDENTIFIED BY 'student_54' ;
GRANT Alter ON student_54.* TO 'student_54'@'%';
GRANT Create ON student_54.* TO 'student_54'@'%';
GRANT Create view ON student_54.* TO 'student_54'@'%';
GRANT Delete ON student_54.* TO 'student_54'@'%';
GRANT Drop ON student_54.* TO 'student_54'@'%';
GRANT Grant option ON student_54.* TO 'student_54'@'%';
GRANT Index ON student_54.* TO 'student_54'@'%';
GRANT Insert ON student_54.* TO 'student_54'@'%';
GRANT References ON student_54.* TO 'student_54'@'%';
GRANT Select ON student_54.* TO 'student_54'@'%';
GRANT Show view ON student_54.* TO 'student_54'@'%';
GRANT Trigger ON student_54.* TO 'student_54'@'%';
GRANT Update ON student_54.* TO 'student_54'@'%';
GRANT Alter routine ON student_54.* TO 'student_54'@'%';
GRANT Create routine ON student_54.* TO 'student_54'@'%';
GRANT Create temporary tables ON student_54.* TO 'student_54'@'%';
GRANT Execute ON student_54.* TO 'student_54'@'%';
GRANT Lock tables ON student_54.* TO 'student_54'@'%';

CREATE USER 'student_55'@'%';
ALTER USER 'student_55'@'%'
IDENTIFIED BY 'student_55' ;
GRANT Alter ON student_55.* TO 'student_55'@'%';
GRANT Create ON student_55.* TO 'student_55'@'%';
GRANT Create view ON student_55.* TO 'student_55'@'%';
GRANT Delete ON student_55.* TO 'student_55'@'%';
GRANT Drop ON student_55.* TO 'student_55'@'%';
GRANT Grant option ON student_55.* TO 'student_55'@'%';
GRANT Index ON student_55.* TO 'student_55'@'%';
GRANT Insert ON student_55.* TO 'student_55'@'%';
GRANT References ON student_55.* TO 'student_55'@'%';
GRANT Select ON student_55.* TO 'student_55'@'%';
GRANT Show view ON student_55.* TO 'student_55'@'%';
GRANT Trigger ON student_55.* TO 'student_55'@'%';
GRANT Update ON student_55.* TO 'student_55'@'%';
GRANT Alter routine ON student_55.* TO 'student_55'@'%';
GRANT Create routine ON student_55.* TO 'student_55'@'%';
GRANT Create temporary tables ON student_55.* TO 'student_55'@'%';
GRANT Execute ON student_55.* TO 'student_55'@'%';
GRANT Lock tables ON student_55.* TO 'student_55'@'%';

CREATE USER 'student_56'@'%';
ALTER USER 'student_56'@'%'
IDENTIFIED BY 'student_56' ;
GRANT Alter ON student_56.* TO 'student_56'@'%';
GRANT Create ON student_56.* TO 'student_56'@'%';
GRANT Create view ON student_56.* TO 'student_56'@'%';
GRANT Delete ON student_56.* TO 'student_56'@'%';
GRANT Drop ON student_56.* TO 'student_56'@'%';
GRANT Grant option ON student_56.* TO 'student_56'@'%';
GRANT Index ON student_56.* TO 'student_56'@'%';
GRANT Insert ON student_56.* TO 'student_56'@'%';
GRANT References ON student_56.* TO 'student_56'@'%';
GRANT Select ON student_56.* TO 'student_56'@'%';
GRANT Show view ON student_56.* TO 'student_56'@'%';
GRANT Trigger ON student_56.* TO 'student_56'@'%';
GRANT Update ON student_56.* TO 'student_56'@'%';
GRANT Alter routine ON student_56.* TO 'student_56'@'%';
GRANT Create routine ON student_56.* TO 'student_56'@'%';
GRANT Create temporary tables ON student_56.* TO 'student_56'@'%';
GRANT Execute ON student_56.* TO 'student_56'@'%';
GRANT Lock tables ON student_56.* TO 'student_56'@'%';

CREATE USER 'student_57'@'%';
ALTER USER 'student_57'@'%'
IDENTIFIED BY 'student_57' ;
GRANT Alter ON student_57.* TO 'student_57'@'%';
GRANT Create ON student_57.* TO 'student_57'@'%';
GRANT Create view ON student_57.* TO 'student_57'@'%';
GRANT Delete ON student_57.* TO 'student_57'@'%';
GRANT Drop ON student_57.* TO 'student_57'@'%';
GRANT Grant option ON student_57.* TO 'student_57'@'%';
GRANT Index ON student_57.* TO 'student_57'@'%';
GRANT Insert ON student_57.* TO 'student_57'@'%';
GRANT References ON student_57.* TO 'student_57'@'%';
GRANT Select ON student_57.* TO 'student_57'@'%';
GRANT Show view ON student_57.* TO 'student_57'@'%';
GRANT Trigger ON student_57.* TO 'student_57'@'%';
GRANT Update ON student_57.* TO 'student_57'@'%';
GRANT Alter routine ON student_57.* TO 'student_57'@'%';
GRANT Create routine ON student_57.* TO 'student_57'@'%';
GRANT Create temporary tables ON student_57.* TO 'student_57'@'%';
GRANT Execute ON student_57.* TO 'student_57'@'%';
GRANT Lock tables ON student_57.* TO 'student_57'@'%';

CREATE USER 'student_58'@'%';
ALTER USER 'student_58'@'%'
IDENTIFIED BY 'student_58' ;
GRANT Alter ON student_58.* TO 'student_58'@'%';
GRANT Create ON student_58.* TO 'student_58'@'%';
GRANT Create view ON student_58.* TO 'student_58'@'%';
GRANT Delete ON student_58.* TO 'student_58'@'%';
GRANT Drop ON student_58.* TO 'student_58'@'%';
GRANT Grant option ON student_58.* TO 'student_58'@'%';
GRANT Index ON student_58.* TO 'student_58'@'%';
GRANT Insert ON student_58.* TO 'student_58'@'%';
GRANT References ON student_58.* TO 'student_58'@'%';
GRANT Select ON student_58.* TO 'student_58'@'%';
GRANT Show view ON student_58.* TO 'student_58'@'%';
GRANT Trigger ON student_58.* TO 'student_58'@'%';
GRANT Update ON student_58.* TO 'student_58'@'%';
GRANT Alter routine ON student_58.* TO 'student_58'@'%';
GRANT Create routine ON student_58.* TO 'student_58'@'%';
GRANT Create temporary tables ON student_58.* TO 'student_58'@'%';
GRANT Execute ON student_58.* TO 'student_58'@'%';
GRANT Lock tables ON student_58.* TO 'student_58'@'%';

CREATE USER 'student_59'@'%';
ALTER USER 'student_59'@'%'
IDENTIFIED BY 'student_59' ;
GRANT Alter ON student_59.* TO 'student_59'@'%';
GRANT Create ON student_59.* TO 'student_59'@'%';
GRANT Create view ON student_59.* TO 'student_59'@'%';
GRANT Delete ON student_59.* TO 'student_59'@'%';
GRANT Drop ON student_59.* TO 'student_59'@'%';
GRANT Grant option ON student_59.* TO 'student_59'@'%';
GRANT Index ON student_59.* TO 'student_59'@'%';
GRANT Insert ON student_59.* TO 'student_59'@'%';
GRANT References ON student_59.* TO 'student_59'@'%';
GRANT Select ON student_59.* TO 'student_59'@'%';
GRANT Show view ON student_59.* TO 'student_59'@'%';
GRANT Trigger ON student_59.* TO 'student_59'@'%';
GRANT Update ON student_59.* TO 'student_59'@'%';
GRANT Alter routine ON student_59.* TO 'student_59'@'%';
GRANT Create routine ON student_59.* TO 'student_59'@'%';
GRANT Create temporary tables ON student_59.* TO 'student_59'@'%';
GRANT Execute ON student_59.* TO 'student_59'@'%';
GRANT Lock tables ON student_59.* TO 'student_59'@'%';

CREATE USER 'student_60'@'%';
ALTER USER 'student_60'@'%'
IDENTIFIED BY 'student_60' ;
GRANT Alter ON student_60.* TO 'student_60'@'%';
GRANT Create ON student_60.* TO 'student_60'@'%';
GRANT Create view ON student_60.* TO 'student_60'@'%';
GRANT Delete ON student_60.* TO 'student_60'@'%';
GRANT Drop ON student_60.* TO 'student_60'@'%';
GRANT Grant option ON student_60.* TO 'student_60'@'%';
GRANT Index ON student_60.* TO 'student_60'@'%';
GRANT Insert ON student_60.* TO 'student_60'@'%';
GRANT References ON student_60.* TO 'student_60'@'%';
GRANT Select ON student_60.* TO 'student_60'@'%';
GRANT Show view ON student_60.* TO 'student_60'@'%';
GRANT Trigger ON student_60.* TO 'student_60'@'%';
GRANT Update ON student_60.* TO 'student_60'@'%';
GRANT Alter routine ON student_60.* TO 'student_60'@'%';
GRANT Create routine ON student_60.* TO 'student_60'@'%';
GRANT Create temporary tables ON student_60.* TO 'student_60'@'%';
GRANT Execute ON student_60.* TO 'student_60'@'%';
GRANT Lock tables ON student_60.* TO 'student_60'@'%';

GRANT Select ON thaneea.* TO 'student_1'@'%';
GRANT Select ON thaneea.* TO 'student_2'@'%';
GRANT Select ON thaneea.* TO 'student_3'@'%';
GRANT Select ON thaneea.* TO 'student_4'@'%';
GRANT Select ON thaneea.* TO 'student_5'@'%';
GRANT Select ON thaneea.* TO 'student_6'@'%';
GRANT Select ON thaneea.* TO 'student_7'@'%';
GRANT Select ON thaneea.* TO 'student_8'@'%';
GRANT Select ON thaneea.* TO 'student_9'@'%';
GRANT Select ON thaneea.* TO 'student_10'@'%';
GRANT Select ON thaneea.* TO 'student_11'@'%';
GRANT Select ON thaneea.* TO 'student_12'@'%';
GRANT Select ON thaneea.* TO 'student_13'@'%';
GRANT Select ON thaneea.* TO 'student_14'@'%';
GRANT Select ON thaneea.* TO 'student_15'@'%';
GRANT Select ON thaneea.* TO 'student_16'@'%';
GRANT Select ON thaneea.* TO 'student_17'@'%';
GRANT Select ON thaneea.* TO 'student_18'@'%';
GRANT Select ON thaneea.* TO 'student_19'@'%';
GRANT Select ON thaneea.* TO 'student_20'@'%';
GRANT Select ON thaneea.* TO 'student_21'@'%';
GRANT Select ON thaneea.* TO 'student_22'@'%';
GRANT Select ON thaneea.* TO 'student_23'@'%';
GRANT Select ON thaneea.* TO 'student_24'@'%';
GRANT Select ON thaneea.* TO 'student_25'@'%';
GRANT Select ON thaneea.* TO 'student_26'@'%';
GRANT Select ON thaneea.* TO 'student_27'@'%';
GRANT Select ON thaneea.* TO 'student_28'@'%';
GRANT Select ON thaneea.* TO 'student_29'@'%';
GRANT Select ON thaneea.* TO 'student_30'@'%';
GRANT Select ON thaneea.* TO 'student_31'@'%';
GRANT Select ON thaneea.* TO 'student_32'@'%';
GRANT Select ON thaneea.* TO 'student_33'@'%';
GRANT Select ON thaneea.* TO 'student_34'@'%';
GRANT Select ON thaneea.* TO 'student_35'@'%';
GRANT Select ON thaneea.* TO 'student_36'@'%';
GRANT Select ON thaneea.* TO 'student_37'@'%';
GRANT Select ON thaneea.* TO 'student_38'@'%';
GRANT Select ON thaneea.* TO 'student_39'@'%';
GRANT Select ON thaneea.* TO 'student_40'@'%';
GRANT Select ON thaneea.* TO 'student_41'@'%';
GRANT Select ON thaneea.* TO 'student_42'@'%';
GRANT Select ON thaneea.* TO 'student_43'@'%';
GRANT Select ON thaneea.* TO 'student_44'@'%';
GRANT Select ON thaneea.* TO 'student_45'@'%';
GRANT Select ON thaneea.* TO 'student_46'@'%';
GRANT Select ON thaneea.* TO 'student_47'@'%';
GRANT Select ON thaneea.* TO 'student_48'@'%';
GRANT Select ON thaneea.* TO 'student_49'@'%';
GRANT Select ON thaneea.* TO 'student_50'@'%';
GRANT Select ON thaneea.* TO 'student_51'@'%';
GRANT Select ON thaneea.* TO 'student_52'@'%';
GRANT Select ON thaneea.* TO 'student_53'@'%';
GRANT Select ON thaneea.* TO 'student_54'@'%';
GRANT Select ON thaneea.* TO 'student_55'@'%';
GRANT Select ON thaneea.* TO 'student_56'@'%';
GRANT Select ON thaneea.* TO 'student_57'@'%';
GRANT Select ON thaneea.* TO 'student_58'@'%';
GRANT Select ON thaneea.* TO 'student_59'@'%';
GRANT Select ON thaneea.* TO 'student_60'@'%';
